### PR TITLE
Fix invalid escape sequences

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
@davidemoro look good?

**Comment by davidemoro** [comment]
Hi @asottile,

thanks for your contribution, looks fine!

I am sorry because of my late response (I am on holiday). Could you add a changelog note please?

**Comment by asottile** [comment]
No problem 🎉  done!

**Comment by davidemoro** [comment]
Thanks @asottile, merged!

**Pull request merged**
